from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ctdui_v40.lua"

CORE_PARTS = [ROOT / "src" / f"part{i:02d}.lua.txt" for i in range(1, 17)]
PATCHES = [
    ROOT / "patches" / "autoexec_v17.lua",
    ROOT / "patches" / "pregame_v19.lua",
    ROOT / "patches" / "player_v20.lua",
    ROOT / "patches" / "w0_v30.lua",
    ROOT / "patches" / "endaction_v31.lua",
    ROOT / "patches" / "input_v32.lua",
    ROOT / "patches" / "reliability_v39.lua",
    ROOT / "patches" / "webhook_v39.lua",
    ROOT / "patches" / "endclick_v39.lua",
]
READY = ROOT / "patches" / "ready_v21.lua"
BASE = ROOT / "ctdui.lua"


def lua_long_string(text: str) -> str:
    # Pick a delimiter that cannot collide with the embedded source.
    for n in range(3, 20):
        eq = "=" * n
        close = f"]{eq}]"
        if close not in text:
            return f"[{eq}[{text}]{eq}]"
    raise RuntimeError("Could not find safe Lua long-string delimiter")


def replace_fetch_parts(base: str, core: str) -> str:
    pattern = re.compile(
        r"local function fetchParts\(base, count, workers\).*?"
        r"local coreSource = fetchParts\(\s*"
        r'"https://raw\.githubusercontent\.com/evilxoma/xomahub/refs/heads/main/src/",\s*'
        r"16,\s*4\s*\)\s*",
        re.S,
    )
    replacement = "local coreSource = " + lua_long_string(core) + "\n\n"
    updated, count = pattern.subn(lambda _: replacement, base, count=1)
    if count != 1:
        raise RuntimeError("Could not replace ctdui fetchParts/coreSource block")
    return updated


def strip_runtime_patch_loader(base: str) -> str:
    marker = "local autoexecSource = game:HttpGet("
    index = base.find(marker)
    if index < 0:
        raise RuntimeError("Could not locate runtime patch loader block")
    return base[:index].rstrip() + "\n\n"


def inline_ready_into_player(player_source: str, ready_source: str) -> str:
    pattern = re.compile(
        r"local readySource = game:HttpGet\(\s*"
        r'"https://raw\.githubusercontent\.com/evilxoma/xomahub/refs/heads/main/patches/ready_v21\.lua"\s*'
        r"\)\s*",
        re.S,
    )
    replacement = "local readySource = " + lua_long_string(ready_source) + "\n"
    updated, count = pattern.subn(lambda _: replacement, player_source, count=1)
    if count != 1:
        raise RuntimeError("Could not inline ready_v21.lua into player_v20.lua")
    return updated


def v40_patch_source(path: Path, source: str) -> str:
    # V39's three active top-level patches become V40 in the monolith. Older
    # compatibility patches keep their historic internal build names so their
    # idempotency/state checks remain unchanged.
    if path.name in {"reliability_v39.lua", "webhook_v39.lua", "endclick_v39.lua"}:
        source = source.replace("ctdui_v39.lua", "ctdui_v40.lua")
        source = source.replace("V39", "V40")
        source = source.replace("v39", "v40")
        source = source.replace("PASS29-", "PASS30-MONOLITH-")
    return source


def chunk_runner(label: str, source: str) -> str:
    return (
        f"do\n"
        f"    local source = {lua_long_string(source)}\n"
        f"    local chunk, err = loadstring(source)\n"
        f"    if not chunk then error({label!r} .. ' compile failed: ' .. tostring(err)) end\n"
        f"    XOMA = chunk() or XOMA\n"
        f"end\n\n"
    ).replace("'", '"')


def main() -> None:
    core = "\n".join(path.read_text(encoding="utf-8") for path in CORE_PARTS)
    base = BASE.read_text(encoding="utf-8")
    base = replace_fetch_parts(base, core)
    base = strip_runtime_patch_loader(base)
    base = base.replace("ctdui_v33.lua", "ctdui_v40.lua")
    base = base.replace("PASS23-NONBLOCKING-SKIP-V33", "PASS30-MONOLITH-V40")

    ready = READY.read_text(encoding="utf-8")
    chunks = []
    for path in PATCHES:
        source = path.read_text(encoding="utf-8")
        if path.name == "player_v20.lua":
            source = inline_ready_into_player(source, ready)
        source = v40_patch_source(path, source)
        chunks.append(chunk_runner(f"XOMA monolith {path.name}", source))

    output = (
        "-- XOMA / CTDIG MONOLITH\n"
        "-- Build: PASS30-MONOLITH-V40\n"
        "-- Generated by tools/build_v40_monolith.py.\n"
        "-- Runtime has no xomahub src/patches HttpGet dependencies; all active\n"
        "-- CTDIG source and patches are embedded below as isolated loadstring chunks.\n\n"
        + base
        + "local XOMA = XOMA\n\n"
        + "".join(chunks)
        + "local environment = typeof(getgenv) == \"function\" and getgenv() or _G\n"
        + "local activeSession = environment.CTDIG_SESSION\n"
        + "if type(activeSession) == \"table\" then\n"
        + "    activeSession.bootstrapBuild = \"PASS30-MONOLITH-V40\"\n"
        + "end\n"
        + "print(\"[XOMA V40] monolith loaded | single-file runtime\")\n"
        + "return XOMA\n"
    )

    # A monolith may still contain game:HttpGet for third-party UI/assets inside
    # the original core, but it must not fetch our own split src/patches files.
    forbidden = re.findall(
        r"https://raw\.githubusercontent\.com/evilxoma/xomahub/[^\"']+/(?:src|patches)/[^\"']+",
        output,
    )
    if forbidden:
        raise RuntimeError("Monolith still contains xomahub split dependency: " + forbidden[0])

    if "ctdui_v39.lua" in output:
        raise RuntimeError("V39 recorder/bootstrap URL survived V40 build")
    if "ctdui_v40.lua" not in output:
        raise RuntimeError("V40 recorder/bootstrap URL is missing")

    OUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.name}: {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
